# .github/workflows/node-build.yml
name: Deploy to Azure Arquitecture


on:
  workflow_call:


jobs:
  deploy-azure-arquitecture:
    name: Arquitecture
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Clone terraform scripts repository
        uses: actions/checkout@v4
        with:
          repository: codeparce/azure-terraform
          token: ${{ secrets.PERSONAL_ACCES_TOKEN }}
          path: azure-terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Deploy Azure infrastructure
        run: |
          cd azure-terraform/2-static-web-app
          bash azure_deploy_arquitecture.sh

      - name: Upload Static Web App secrets artifact
        uses: actions/upload-artifact@v4
        with:
          name: static-web-app-secrets
          path: azure-terraform/2-static-web-app/secret
          retention-days: 1
