# .github/workflows/build-code.yml
name: Build code


on:
  workflow_call:


jobs:
  zip-code:
    name: Zip Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: zip code
        run: |
          ls && cd function/ && zip -r functions.zip . -x "*test*"

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: file.zip
          path: function/functions.zip
          retention-days: 1
          
  push-code:
    name: Push Code
    runs-on: ubuntu-latest
    needs: [zip-code]
    env:
      VAULT_USER: ${{ secrets.VAULT_USER }}
      VAULT_PASS: ${{ secrets.VAULT_PASS }}
      VAULT_ADDR: ${{ secrets.VAULT_ADDR }}  
      VAULT_NAMESPACE: ${{ secrets.VAULT_NAMESPACE }}  
      GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Download zip artifact
        uses: actions/download-artifact@v4
        with:
          name: file.zip
          path: function

      - name: Clone terraform scripts repository
        uses: actions/checkout@v4
        with:
          repository: codeparceorg/terraform-cloud
          ref: gcp
          token: ${{ secrets.PERSONAL_ACCES_TOKEN }}
          path: terraform-cloud

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: '>= 363.0.0'

      - name: Push zip to bucket
        run: |
          bash terraform-cloud/3-functions/upload_zip.sh
